#ifndef _AX_WEBSOCKETS_VERSION_H_
#define _AX_WEBSOCKETS_VERSION_H_


#define AX_WEBSOCKETS_VERSION_MAJOR 1
#define AX_WEBSOCKETS_VERSION_MINOR 0
#define AX_WEBSOCKETS_VERSION_PATCH 0

#define AX_WEBSOCKETS_VERSION "1.0.0"

#endif //_AX_WEBSOCKETS_VERSION_H_
